models/contact.py
import email
from utils.db import db


class Contact(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    fullname = db.Column(db.String(100))
    email = db.Column(db.String(100))
    phone = db.Column(db.String(100))

    def __init__(self, fullname, email, phone):
        self.fullname = fullname
        self.email = email
        self.phone = phone

app.py
from flask import Flask
from routes.contacts import contacts
from flask_sqlalchemy import SQLAlchemy
from config import DATABASE_CONNECTION_URIL

app = Flask(__name__)

app.secret_key = "secret key"
# app.config['SQLALCHEMY_DATABASE_URI'] = DATABASE_CONNECTION_URIL
app.config['SQLALCHEMY_DATABASE_URI'] = "sqlite:///db/contactsdb.db"
app.config['SQLALCHEMY_TRACK_MODIFICATIONS'] = False

SQLAlchemy(app)

app.register_blueprint(contacts)

routes/contacts.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from models.contact import Contact
from utils.db import db

contacts = Blueprint("contacts", __name__)


@contacts.route("/")
def home():
    contacts = Contact.query.all()
    return render_template('index.html', contacts=contacts)


@contacts.route("/new", methods=['POST'])
def add_contact():
    fullname = request.form["fullname"]
    email = request.form["email"]
    phone = request.form["phone"]

    new_contact = Contact(fullname, email, phone)

    db.session.add(new_contact)
    db.session.commit()

    flash("Contact added succcesfully")

    return redirect(url_for('contacts.home'))


@contacts.route("/update/<id>", methods=["POST", "GET"])
def update(id):
    contact = Contact.query.get(id)
    if request.method == "POST":
        contact.fullname = request.form["fullname"]
        contact.email = request.form["email"]
        contact.phone = request.form["phone"]

        db.session.commit()

        flash("Contact updated successfully")

        return redirect(url_for("contacts.home"))

    return render_template("update.html", contact=contact)


@contacts.route("/delete/<id>")
def delete(id):
    contact = Contact.query.get(id)
    db.session.delete(contact)
    db.session.commit()

    flash("Contact deleted successfully")

    return redirect(url_for('contacts.home'))


@contacts.route("/about")
def about():
    return render_template("about.html")

templates/index.html
{% extends 'layout.html' %} {% block content %}

<div class="row">
  <div class="col-md-5">
    {% include 'partials/_messages.html' %} {%
    include('partials/_contactForm.html') %}
  </div>

  <div class="col-md-7">
    {% for contact in contacts %}

    <div class="card mb-1 text-white bg-dark">
      <div class="card-body">
        <div class="d-flex justify-content-between">
          <h5>{{contact.fullname}}</h5>
          <div>
            <a
              href="{{ url_for('contacts.update', id=contact.id) }}"
              class="btn btn-black text-white btn-sm rounded-0"
              >Update</a
            >
            <a
              href="{{ url_for('contacts.delete', id=contact.id) }}"
              class="btn btn-danger btn-sm rounded-0"
              >Delete</a
            >
          </div>
        </div>
        <p>{{contact.email}}</p>
        <p>{{contact.phone}}</p>
      </div>
    </div>

    {% endfor %}
  </div>
</div>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Flask SQLAlchemy CRUD</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href={{url_for('static', filename='css/main.css')}}>
  </head>
  <body>

    {% include('partials/_navbar.html') %}

    <div class="container p-2">
      {% block content %} 
      {% endblock %}
    </div>
  </body>

  <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
      crossorigin="anonymous"
    ></script>
</html>

templates/partials/_contactForm.html
<form action="/new" method="POST" class="card bg-dark text-light">
  <div class="card-body p-4">
    <div class="mb-3">
      <label for="fullname">Write your fullname:</label>
      <input
        type="text"
        name="fullname"
        placeholder="Write your fullname"
        class="form-control rounded-0 bg-dark border-0 text-white"
      />
    </div>
    <div class="mb-3">
      <label for="email">Write your email:</label>
      <input
      type="text"
      name="email"
      placeholder="Write your email"
      class="form-control rounded-0 bg-dark border-0 text-white"
    />
    </div>
    <div class="mb-3">
      <label for="phone">Write your phone</label>
      <input
      type="text"
      name="phone"
      placeholder="Write your phone"
      class="form-control rounded-0 bg-dark border-0 text-white"
    />
    </div>

    <button class="btn btn-success">Save</button>
  </div>
</form>

templates/partials/_messages.html
{% with messages = get_flashed_messages() %}

  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-warning alert-dismissible fade show" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
          <span aria-hidden="true"></span>
        </button>
      </div>
    {% endfor %}
  {% endif %}

{% endwith %}

templates/partials/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="/">Flask SQLAlcehmy CRUD</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarNav"
      aria-controls="navbarNav"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/about">Home</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/update.html
{% extends 'layout.html' %}  

{% block content %}

<div class="row">
  <div class="col-lg-4 offset-lg-4">
    <form action="/update/{{ contact.id }}" method="POST">
      <div class="card-body p-4">
        <div class="mb-3">
          <label class="text-white" for="fullname">Update your fullname:</label>
          <input
          type="text"
          name="fullname"
          placeholder="Write your fullname"
          value="{{contact.fullname}}"
          class="form-control rounded-0 bg-dark border-0 text-white"
          />
        </div>
      
        <div class="mb-3">
          <label class="text-white" for="fullname">Update your email:</label>
          <input
          type="text"
          name="email"
          placeholder="Write your email"
          value="{{contact.email}}"
          class="form-control rounded-0 bg-dark border-0 text-white"
          />
        </div>
      
        <div class="mb-3">
          <label class="text-white" for="fullname">Update your phone:</label>
          <input
          type="text"
          name="phone"
          placeholder="Write your phone"
          value="{{contact.phone}}"
          class="form-control rounded-0 bg-dark border-0 text-white"
          />
        </div>
      
        <button class="btn btn-secondary">Update</button>
      </div>
    </form>
  </div>
</div>

{% endblock %}